// StudyForge 4.0 Personal OS layer.
// Loaded last. Adds adaptive productivity controls without cluttering the Today screen.

function sf40OS(){
  S.os=S.os||{};
  const o=S.os;
  o.dayOverrides=o.dayOverrides||{};
  o.fixedEvents=o.fixedEvents||{};
  o.recurring=o.recurring||[];
  o.taskMeta=o.taskMeta||{};
  o.planHistory=o.planHistory||{};
  o.dailyReviews=o.dailyReviews||{};
  o.notes=o.notes||[];
  o.tomorrowDraft=o.tomorrowDraft||{};
  o.settings=Object.assign({workloadMode:'balanced',energy:'normal',sleepStart:'23:00',bufferMinutes:10,maxFocusMinutes:360,noGuilt:true,modules:{prayer:true,battery:true,habits:true,analytics:true}},o.settings||{});
  return o;
}
function sf40Meta(id){const o=sf40OS();o.taskMeta[id]=o.taskMeta[id]||{progress:0,difficulty:'medium',dependencies:[],confidence:null,notes:'',skipReason:'',pauseReasons:[]};return o.taskMeta[id]}
function sf40TomorrowKey(){const d=new Date();d.setDate(d.getDate()+1);return keyFor(d)}
function sf40DateObj(k){const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d)}
function sf40Snapshot(reason='manual'){
  const o=sf40OS(),k=keyFor();o.planHistory[k]=o.planHistory[k]||[];
  o.planHistory[k].push({at:Date.now(),reason,plan:clone(todayPlan()),tasks:clone(S.tasks),checks:clone(checks())});
  o.planHistory[k]=o.planHistory[k].slice(-12);save();
}
function sf40Undo(){const o=sf40OS(),k=keyFor(),h=o.planHistory[k]||[];const snap=h.pop();if(!snap)return toast('No earlier plan to restore');S.plans[k]=snap.plan;S.tasks=snap.tasks;S.checks[k]=snap.checks;o.planHistory[k]=h;save();render();toast('Previous plan restored')}
function sf40Override(){const o=sf40OS(),k=keyFor();return o.dayOverrides[k]||{mode:o.settings.workloadMode,energy:o.settings.energy,limitMinutes:null,emergency:false}}
function sf40ModeCap(){const x=sf40Override(),map={light:150,balanced:300,intense:420,deadline:540};let cap=map[x.mode]||300;if(x.energy==='low')cap=Math.round(cap*.65);if(x.energy==='high')cap=Math.round(cap*1.12);if(x.limitMinutes)cap=Math.min(cap,Number(x.limitMinutes));return Math.max(30,cap)}
function sf40IsFixed(item){return ['routine','break','prayer','event'].includes(item?.type)||Boolean(item?.hardFixed)}
function sf33IsWork(item){return !['routine','break','prayer','event'].includes(item?.type)}
function sf40AllActuals(){const rows=[];for(const [date,L] of Object.entries(S.liveByDate||{})){for(const [id,a] of Object.entries(L.actuals||{})){const p=(S.plans?.[date]||[]).find(x=>x.id===id);rows.push({date,id,skill:p?.skill||'General',type:p?.type||'task',...a})}}return rows}
function sf40Velocity(skill){const rows=sf40AllActuals().filter(x=>x.skill===skill&&x.actualMinutes>0&&x.plannedMinutes>0).slice(-12);if(rows.length<2)return 1;const r=rows.reduce((n,x)=>n+x.actualMinutes/x.plannedMinutes,0)/rows.length;return Math.max(.65,Math.min(1.8,r))}
function sf40Estimate(task){const meta=sf40Meta(task.id),difficulty={easy:.85,medium:1,hard:1.2}[meta.difficulty]||1;return Math.max(15,Math.min(180,Math.round((Number(task.duration)||S.profile.sessionMinutes)*sf40Velocity(task.skill||'General')*difficulty/5)*5))}
function sf40Capacity(){const hours=activeHours().length*60,cap=Math.min(hours,sf40ModeCap());const fixed=todayPlan().filter(sf40IsFixed).reduce((n,x)=>n+(Number(x.duration)||0),0);return {available:Math.max(0,hours-fixed),cap:Math.max(0,Math.min(cap,hours-fixed))}}
function sf40PlannedWorkMinutes(){return todayPlan().filter(x=>sf33IsWork(x)&&!sf33IsDone(x.id)).reduce((n,x)=>n+(Number(x.duration)||0),0)}
function sf40Top3(){return todayPlan().filter(x=>sf33IsWork(x)&&!sf33IsDone(x.id)).sort((a,b)=>{const p={high:0,medium:1,low:2};return (p[a.priority]??1)-(p[b.priority]??1)||mins(a.time)-mins(b.time)}).slice(0,3)}
function sf40AddFixedEvents(plan){const events=sf40OS().fixedEvents[keyFor()]||[];const ids=new Set(plan.map(x=>x.id));for(const e of events){if(!ids.has(e.id))plan.push({...e,skill:'Fixed event',type:'event',priority:'high',locked:true,hardFixed:true,emoji:e.emoji||'📌',reason:e.reason||'Fixed appointment'})}return plan.sort((a,b)=>mins(a.time)-mins(b.time))}
function sf40InjectRecurring(){const o=sf40OS(),day=new Date().getDay(),k=keyFor();for(const r of o.recurring){if(!r.days?.includes(day))continue;const id=`rec-${k}-${r.id}`;if(S.tasks.some(t=>t.id===id)||todayPlan().some(t=>t.id===id))continue;S.tasks.push({id,title:r.title,skill:r.skill||'Routine',duration:r.duration||30,priority:r.priority||'medium',deadline:'',done:false,type:r.type||'task',recurringId:r.id})}}
function sf40ApplyPolicy(){
  sf40InjectRecurring();const o=sf40OS(),override=sf40Override();let plan=sf40AddFixedEvents(todayPlan().map(x=>({...x})));
  if(override.emergency){for(const x of plan.filter(sf33IsWork))sf33CarryToBank(x);plan=plan.filter(x=>!sf33IsWork(x));}
  const cap=sf40ModeCap();let used=0;
  for(const x of plan.sort((a,b)=>mins(a.time)-mins(b.time))){if(!sf33IsWork(x)||sf33IsDone(x.id))continue;const est=sf40Estimate(x);x.duration=est;if(used+est>cap&&!x.locked){x._deferred=true;sf33CarryToBank(x)}else used+=est}
  plan=plan.filter(x=>!x._deferred);S.plans[keyFor()]=plan;save();
}
const sf40BaseGeneratePlan=generatePlan;
generatePlan=async function(silent=false){sf40Snapshot('before AI re-plan');await sf40BaseGeneratePlan(silent);sf40ApplyPolicy();render()}
const sf40BaseStart=sf33StartTask;
sf33StartTask=function(id){const m=sf40Meta(id),blocked=(m.dependencies||[]).filter(dep=>!sf33IsDone(dep));if(blocked.length){toast(`Complete ${blocked.length} prerequisite task${blocked.length>1?'s':''} first`);return}sf40BaseStart(id)}
function sf40QuickDay(){const x=sf40Override();document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h3>Quick day override</h3><div class="note">Changes today only. Your normal weekly setup stays untouched.</div><label class="label">DAY MODE</label><div class="grid2">${['light','balanced','intense','deadline'].map(v=>`<button class="mode ${x.mode===v?'active':''}" data-daymode="${v}">${v}</button>`).join('')}</div><label class="label">ENERGY</label><div class="grid3">${['low','normal','high'].map(v=>`<button class="mode ${x.energy===v?'active':''}" data-energy="${v}">${v}</button>`).join('')}</div><label class="label">MAX FOCUS TODAY</label><select id="sf40Limit" class="select"><option value="">Automatic</option>${[60,120,180,240,300,360].map(n=>`<option value="${n}" ${x.limitMinutes===n?'selected':''}>${n/60}h</option>`).join('')}</select><div class="switchrow card" style="margin-top:12px"><div><b>Emergency day reset</b><div class="note">Keep fixed events/routines; move flexible work out.</div></div><button id="sf40Emergency" class="switch ${x.emergency?'on':''}"><i></i></button></div><button class="btn" onclick="sf40SaveQuickDay()">Apply + reflow</button></div></div>`;document.querySelectorAll('[data-daymode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-daymode]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.querySelectorAll('[data-energy]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-energy]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});document.getElementById('sf40Emergency').onclick=e=>e.currentTarget.classList.toggle('on')}
function sf40SaveQuickDay(){const o=sf40OS(),k=keyFor();sf40Snapshot('before day override');o.dayOverrides[k]={mode:document.querySelector('[data-daymode].active')?.dataset.daymode||'balanced',energy:document.querySelector('[data-energy].active')?.dataset.energy||'normal',limitMinutes:Number(document.getElementById('sf40Limit').value)||null,emergency:document.getElementById('sf40Emergency').classList.contains('on')};save();closeModal();sf40ApplyPolicy();sf33CommitReflow(sf33NowMinute());render();toast('Today adapted')}
function sf40Partial(id){const task=todayPlan().find(x=>x.id===id);if(!task)return;const current=sf40Meta(id).progress||0;document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h3>Partial completion</h3><div class="note">${esc(task.title)}</div><label class="label">PROGRESS</label><div class="grid3">${[25,50,75].map(n=>`<button class="mode ${current===n?'active':''}" onclick="sf40SavePartial('${id}',${n})">${n}%</button>`).join('')}</div><button class="btn green" onclick="sf40SavePartial('${id}',100)">100% complete</button></div></div>`}
function sf40SavePartial(id,pct){const task=todayPlan().find(x=>x.id===id);if(!task)return;const meta=sf40Meta(id);meta.progress=pct;if(pct>=100){closeModal();if(sf34LiveState().activeId===id)sf33CompleteActive();else{S.checks[keyFor()]=S.checks[keyFor()]||{};S.checks[keyFor()][id]=true;save();render()}return}const original=Number(task.originalDuration||task.duration)||S.profile.sessionMinutes;task.originalDuration=original;task.duration=Math.max(10,Math.round(original*(100-pct)/100));if(sf34LiveState().activeId===id){const L=sf34LiveState();L.activeId=null;L.startedAt=null;L.pausedAt=null;L.totalPausedMs=0}sf40Snapshot('partial completion');sf33CommitReflow(sf33NowMinute());save();closeModal();render();toast(`${pct}% saved; remaining work reflowed`)}
function sf40Split(id){const bank=S.tasks.find(x=>x.id===id),plan=todayPlan().find(x=>x.id===id),t=bank||plan;if(!t)return;const total=Number(t.duration)||S.profile.sessionMinutes;if(total<=45)return toast('This task is already a small block');const chunk=Math.min(50,S.profile.sessionMinutes||50),count=Math.ceil(total/chunk),arr=[];let left=total;for(let i=1;i<=count;i++){const d=Math.min(chunk,left);arr.push({id:`${t.id}-part-${i}-${Date.now()}`,title:`${t.title} · Part ${i}/${count}`,skill:t.skill||'General',duration:d,priority:t.priority||'medium',deadline:t.deadline||'',done:false,type:t.type||'task'});left-=d}S.tasks=S.tasks.filter(x=>x.id!==t.id).concat(arr);S.plans[keyFor()]=todayPlan().filter(x=>x.id!==t.id);save();render();toast(`Split into ${count} focused blocks`)}
function sf40TaskDetail(id){const t=todayPlan().find(x=>x.id===id)||S.tasks.find(x=>x.id===id);if(!t)return;const m=sf40Meta(id),candidates=[...todayPlan(),...S.tasks].filter(x=>x.id!==id&&sf33IsWork(x)).slice(0,12);document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h3>${esc(t.title)}</h3><div class="note">Estimated ${sf40Estimate(t)}m · velocity ×${sf40Velocity(t.skill||'General').toFixed(2)}</div><label class="label">DIFFICULTY</label><div class="grid3">${['easy','medium','hard'].map(v=>`<button class="mode ${m.difficulty===v?'active':''}" onclick="sf40SetDifficulty('${id}','${v}')">${v}</button>`).join('')}</div><label class="label">NOTES / STOP POINT</label><textarea id="sf40Notes" class="textarea">${esc(m.notes||'')}</textarea><label class="label">DEPENDENCY</label><select id="sf40Dep" class="select"><option value="">None</option>${candidates.map(x=>`<option value="${esc(x.id)}" ${(m.dependencies||[]).includes(x.id)?'selected':''}>${esc(x.title)}</option>`).join('')}</select><button class="btn" onclick="sf40SaveTaskDetail('${id}')">Save details</button><div class="grid2" style="margin-top:8px"><button class="btn secondary" onclick="sf40Split('${id}');closeModal()">Split task</button><button class="btn secondary" onclick="sf40Partial('${id}')">Partial complete</button></div></div></div>`}
function sf40SetDifficulty(id,v){sf40Meta(id).difficulty=v;save();sf40TaskDetail(id)}
function sf40SaveTaskDetail(id){const m=sf40Meta(id);m.notes=document.getElementById('sf40Notes').value.trim();const dep=document.getElementById('sf40Dep').value;m.dependencies=dep?[dep]:[];save();closeModal();render();toast('Task details saved')}
function sf40FixedEvent(){document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h3>Add fixed event</h3><input id="sf40EventTitle" class="input" placeholder="Class, meeting, gym, appointment"><div class="grid2"><div><label class="label">START</label><input id="sf40EventTime" type="time" class="input"></div><div><label class="label">MINUTES</label><input id="sf40EventDur" type="number" class="input" value="60"></div></div><button class="btn" onclick="sf40SaveEvent()">Protect this time</button></div></div>`}
function sf40SaveEvent(){const title=document.getElementById('sf40EventTitle').value.trim(),time=document.getElementById('sf40EventTime').value,dur=Number(document.getElementById('sf40EventDur').value)||60;if(!title||!time)return toast('Add event and time');const o=sf40OS(),k=keyFor();o.fixedEvents[k]=o.fixedEvents[k]||[];o.fixedEvents[k].push({id:`event-${Date.now()}`,title,time,duration:dur,emoji:'📌'});sf40Snapshot('fixed event');save();closeModal();sf40ApplyPolicy();sf33CommitReflow(sf33NowMinute());render();toast('Fixed event protected')}
function sf40Recurring(){document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h3>Recurring task</h3><input id="sf40RecTitle" class="input" placeholder="English practice"><div class="grid2"><input id="sf40RecSkill" class="input" placeholder="Skill"><input id="sf40RecDur" type="number" class="input" value="30"></div><label class="label">DAYS</label><div class="chips">${DAYS.map((d,i)=>`<button class="chip" data-recday="${i}">${d}</button>`).join('')}</div><button class="btn" onclick="sf40SaveRecurring()">Save recurring task</button></div></div>`;document.querySelectorAll('[data-recday]').forEach(b=>b.onclick=()=>b.classList.toggle('active'))}
function sf40SaveRecurring(){const title=document.getElementById('sf40RecTitle').value.trim(),days=[...document.querySelectorAll('[data-recday].active')].map(x=>Number(x.dataset.recday));if(!title||!days.length)return toast('Add task and days');sf40OS().recurring.push({id:`r-${Date.now()}`,title,skill:document.getElementById('sf40RecSkill').value.trim()||'Routine',duration:Number(document.getElementById('sf40RecDur').value)||30,priority:'medium',days});save();closeModal();sf40InjectRecurring();render();toast('Recurring task saved')}
function sf40BrainDump(){document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h3>Brain dump</h3><div class="note">One line = one task. Optional: “60m”, “high”, “tomorrow”.</div><textarea id="sf40Brain" class="textarea" placeholder="Fix login bug 45m high\nRevise React hooks 30m"></textarea><button class="btn" onclick="sf40ParseBrain()">Turn into tasks</button></div></div>`}
function sf40ParseBrain(){const lines=document.getElementById('sf40Brain').value.split('\n').map(x=>x.trim()).filter(Boolean);for(const line of lines){const mm=line.match(/(\d+)\s*m\b/i),dur=mm?Number(mm[1]):S.profile.sessionMinutes,pri=/\bhigh\b/i.test(line)?'high':/\blow\b/i.test(line)?'low':'medium',title=line.replace(/\b\d+\s*m\b/ig,'').replace(/\b(high|medium|low|tomorrow)\b/ig,'').trim();S.tasks.push({id:`brain-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,title,skill:'General',duration:dur,priority:pri,deadline:'',done:false,type:'task'})}sf40OS().notes.push({at:Date.now(),text:document.getElementById('sf40Brain').value});save();closeModal();render();toast(`${lines.length} task${lines.length===1?'':'s'} added`)}
function sf40WhatNow(){const prayer=sf33OverduePrayer();if(prayer)return toast(`Best next action: complete ${prayer.name}`);const running=sf34LiveState().activeId;if(running){const t=todayPlan().find(x=>x.id===running);return toast(`Continue: ${t?.title||'running task'}`)}const next=sf40Top3()[0];toast(next?`Best next: ${next.title}`:'No urgent work right now')}
function sf40EndDay(){if(sf34LiveState().activeId)return toast('Complete or pause/move the running task first');document.getElementById('modalRoot').innerHTML=`<div class="modal" onclick="if(event.target===this)closeModal()"><div class="sheet"><h3>End my day</h3><label class="label">HOW DID TODAY FEEL?</label><div class="grid3">${['rough','okay','great'].map(x=>`<button class="mode" data-review="${x}">${x}</button>`).join('')}</div><label class="label">ONE NOTE</label><textarea id="sf40ReviewNote" class="textarea" placeholder="What worked or what got in the way?"></textarea><button class="btn green" onclick="sf40FinishDay()">Close day + draft tomorrow</button></div></div>`;document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-review]').forEach(x=>x.classList.remove('active'));b.classList.add('active')})}
function sf40FinishDay(){const o=sf40OS(),k=keyFor(),feeling=document.querySelector('[data-review].active')?.dataset.review||'okay',note=document.getElementById('sf40ReviewNote').value.trim();const unfinished=todayPlan().filter(x=>sf33IsWork(x)&&!sf33IsDone(x.id));for(const t of unfinished)sf33CarryToBank(t);o.dailyReviews[k]={at:Date.now(),feeling,note,unfinished:unfinished.length};const pending=S.tasks.filter(x=>!x.done).sort((a,b)=>({high:0,medium:1,low:2}[a.priority]??1)-({high:0,medium:1,low:2}[b.priority]??1)).slice(0,6);o.tomorrowDraft[sf40TomorrowKey()]=pending.map((t,i)=>({...t,id:`draft-${sf40TomorrowKey()}-${i}`,duration:sf40Estimate(t)}));save();closeModal();render();toast('Day closed; tomorrow draft prepared')}
function sf40WeeklyStats(){const out={done:0,total:0,focus:0,paused:0,late:0,days:0,skills:{}};for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);const k=keyFor(d),p=S.plans[k]||[],c=S.checks[k]||{},work=p.filter(sf33IsWork);if(work.length)out.days++;out.total+=work.length;out.done+=work.filter(x=>c[x.id]).length;const L=S.liveByDate?.[k];for(const [id,a] of Object.entries(L?.actuals||{})){out.focus+=Number(a.actualMinutes)||0;out.paused+=Number(a.pauseMinutes)||0;out.late+=Math.max(0,Number(a.delayMinutes)||0);const item=p.find(x=>x.id===id),skill=item?.skill||'General';out.skills[skill]=(out.skills[skill]||0)+(Number(a.actualMinutes)||0)}}return out}
function sf40Streak(){let n=0;for(let i=0;i<90;i++){const d=new Date();d.setDate(d.getDate()-i);const k=keyFor(d),p=(S.plans[k]||[]).filter(sf33IsWork);if(!p.length){if(i===0)continue;break}const c=S.checks[k]||{};if(p.some(x=>c[x.id]))n++;else break}return n}
function sf40Export(){const blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`studyforge-backup-${keyFor()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup exported')}
function sf40Import(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=()=>{const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(String(r.result));localStorage.setItem(KEY,JSON.stringify(data));location.reload()}catch{toast('Invalid StudyForge backup')}};r.readAsText(f)};input.click()}
function sf40Search(){const q=prompt('Search tasks / notes / history');if(!q)return;const needle=q.toLowerCase(),hits=[];for(const [date,p] of Object.entries(S.plans||{}))for(const t of p)if(`${t.title} ${t.skill} ${t.reason}`.toLowerCase().includes(needle))hits.push(`${date} · ${t.title}`);for(const n of sf40OS().notes)if(n.text.toLowerCase().includes(needle))hits.push(`Note · ${n.text.slice(0,50)}`);alert(hits.slice(0,20).join('\n')||'No matches')}
function sf40SettingsToggle(module){const o=sf40OS();o.settings.modules[module]=!o.settings.modules[module];if(module==='prayer')S.profile.prayerMode=o.settings.modules[module];save();render()}
function sf40CapacityCard(){const c=sf40Capacity(),planned=sf40PlannedWorkMinutes(),pct=c.cap?Math.min(100,Math.round(planned/c.cap*100)):0,status=planned>c.cap?'Overloaded':planned>c.cap*.85?'Busy':'Healthy';return `<div class="card sf40-cap"><div class="ai-row"><div><div class="eyebrow">CAPACITY</div><b>${status}</b></div><div class="sf40-cap-num">${planned} / ${c.cap}m</div></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div><div class="note">Mode ${sf40Override().mode} · energy ${sf40Override().energy}</div></div>`}
function tasksView(){const top=sf40Top3();return `<div class="header"><div><div class="eyebrow">TASK SYSTEM</div><div class="title">Backlog + routing</div></div><button class="btn" onclick="openQuickTask()">+ Add</button></div>${sf40CapacityCard()}${top.length?`<div class="card"><div class="eyebrow">TOP 3 MUST-WIN</div>${top.map((t,i)=>`<div class="sf40-win"><b>${i+1}</b><span>${esc(t.title)}</span><small>${t.duration}m</small></div>`).join('')}</div>`:''}<div class="sf40-tools"><button onclick="sf40QuickDay()">⚡ Day</button><button onclick="sf40BrainDump()">🧠 Dump</button><button onclick="sf40FixedEvent()">📌 Event</button><button onclick="sf40Recurring()">↻ Repeat</button></div>${S.tasks.length?S.tasks.map(t=>{const m=sf40Meta(t.id);return `<div class="task ${t.done?'done':''}"><button class="check ${t.done?'on':''}" onclick="toggleBankTask('${t.id}')">${t.done?'✓':''}</button><div onclick="sf40TaskDetail('${t.id}')"><div class="task-meta">${esc(t.skill)} · ${t.duration}m · ${esc(t.priority)} · ${m.progress||0}%</div><div class="t-title">${esc(t.title)}</div><div class="note">${t.deadline?'Due '+esc(t.deadline):m.dependencies?.length?`${m.dependencies.length} prerequisite`:'Tap for details'}</div></div><button class="delete" onclick="deleteBankTask('${t.id}')">×</button></div>`}).join(''):`<div class="card"><b>Task bank is empty.</b><div class="note">Brain dump or add a task. AI will route work into safe active slots.</div></div>`}<div class="grid2"><button class="btn secondary" onclick="generatePlan(false)">✨ Route tasks</button><button class="btn secondary" onclick="sf40WhatNow()">▶ What now?</button></div>`}
const sf40PrevActiveCard=sf33ActiveCard;
sf33ActiveCard=function(){const L=sf34LiveState();if(!L.activeId)return '';const task=todayPlan().find(x=>x.id===L.activeId);if(!task)return '';const paused=!!L.pausedAt,elapsed=sf33ElapsedMinutes(),planned=Number(task.duration)||S.profile.sessionMinutes,over=Math.max(0,elapsed-planned),pct=Math.min(100,Math.round(elapsed/planned*100));const delay=Math.round(sf33StampMinute(L.startedAt)-mins(task.time));return `<div class="live-card ${paused?'paused':''}"><div class="eyebrow">${paused?'PAUSED':'NOW RUNNING'}</div><div class="live-title" onclick="sf40TaskDetail('${task.id}')">${esc(task.title)}</div><div class="live-clock" data-live-elapsed>${sf33ElapsedLabel()}</div><div class="live-meta"><span>${delay>0?`Started ${delay}m late`:delay<0?`Started ${Math.abs(delay)}m early`:'Started on time'}</span><span data-live-overrun>${paused?`Paused ${sf34PauseLabel()}`:over?`+${over}m over plan`:`${Math.max(0,planned-elapsed)}m planned left`}</span></div><div class="bar"><div class="fill" data-live-progress style="width:${pct}%"></div></div><div class="sf40-live-actions"><button class="btn secondary" onclick="${paused?'sf34ResumeTask()':'sf34PauseTask()'}">${paused?'Resume':'Pause'}</button><button class="btn secondary" onclick="sf40Partial('${task.id}')">Partial</button><button class="btn green" onclick="sf33CompleteActive()">Complete</button></div></div>`}
function progressView(){const w=sf40WeeklyStats(),rate=w.total?Math.round(w.done/w.total*100):0,skillRows=Object.entries(w.skills).sort((a,b)=>b[1]-a[1]).slice(0,6),vel=[...new Set(sf40AllActuals().map(x=>x.skill))].slice(0,6);return `<div class="eyebrow">PROGRESS</div><div class="title">Execution intelligence</div><div class="grid2"><div class="metric"><span class="note">7-day completion</span><b>${rate}%</b></div><div class="metric"><span class="note">Actual focus</span><b>${w.focus}m</b></div><div class="metric"><span class="note">Paused</span><b>${w.paused}m</b></div><div class="metric"><span class="note">Consistency</span><b>${sf40Streak()}d</b></div></div><div class="card" style="margin-top:11px"><div class="eyebrow">SKILL TIME · 7 DAYS</div>${skillRows.length?skillRows.map(([s,m])=>`<div class="sf40-stat"><span>${esc(s)}</span><b>${m}m</b></div>`).join(''):'<div class="note">Complete timed tasks to build skill analytics.</div>'}</div><div class="card"><div class="eyebrow">PERSONAL VELOCITY</div>${vel.length?vel.map(s=>`<div class="sf40-stat"><span>${esc(s)}</span><b>×${sf40Velocity(s).toFixed(2)}</b></div>`).join(''):'<div class="note">After a few completed sessions, StudyForge learns your real pace.</div>'}</div><div class="card"><b>Weekly AI-style review</b><div class="note">${rate>=80?'Strong execution week. Protect the same high-performing windows.':rate>=55?'Solid base. Reduce overload and keep the top 3 visible.':'Plan lighter and protect fewer, more important sessions.'} ${w.paused>90?'Pause time is high; inspect interruptions and buffers.':''}</div></div>`}
function settingsView(){const o=sf40OS(),mods=o.settings.modules;return `<div class="eyebrow">PERSONAL OS</div><div class="title">Planner controls</div><div class="sf40-tools"><button onclick="sf40QuickDay()">⚡ Today</button><button onclick="sf40EndDay()">🌙 End day</button><button onclick="sf40Undo()">↶ Undo</button><button onclick="sf40Search()">⌕ Search</button></div><div class="card"><b>Core setup</b><div class="note">Skills, 24-hour availability, focus block and Prayer Mode.</div><button class="btn" style="width:100%;margin-top:10px" onclick="resetSetup()">Run detailed setup again</button></div><div class="card"><div class="eyebrow">OPTIONAL MODULES</div>${[['prayer','🕌 Prayer'],['battery','🔋 Battery'],['habits','↻ Habits'],['analytics','↗ Analytics']].map(([k,l])=>`<div class="switchrow sf40-switch"><div><b>${l}</b></div><button class="switch ${mods[k]?'on':''}" onclick="sf40SettingsToggle('${k}')"><i></i></button></div>`).join('')}</div><div class="card"><div class="eyebrow">LOCAL-FIRST DATA</div><div class="note">Backup/restore keeps your planner portable without requiring an account.</div><div class="grid2" style="margin-top:10px"><button class="btn secondary" onclick="sf40Export()">Export backup</button><button class="btn secondary" onclick="sf40Import()">Restore</button></div></div><div class="card"><b>Tomorrow draft</b><div class="note">${(o.tomorrowDraft[sf40TomorrowKey()]||[]).length} pending task(s) prepared from today’s backlog.</div></div>${mods.battery?batteryCard():''}`}
const sf40PrevToday=todayView;
todayView=function(){const base=sf40PrevToday();const x=sf40Override(),c=sf40Capacity();return base.replace('<div class="section compact-section">',`<div class="sf40-home-strip"><button onclick="sf40QuickDay()">${x.energy==='low'?'🌙':x.energy==='high'?'⚡':'◉'} ${x.mode}</button><span>${sf40PlannedWorkMinutes()}/${c.cap}m capacity</span><button onclick="sf40WhatNow()">What now?</button></div><div class="section compact-section">`)}

sf40OS();sf40InjectRecurring();sf40ApplyPolicy();save();render();