import { StyleSheet } from 'react-native';
export const C={bg:'#080B12',panel:'#111722',panel2:'#151C28',text:'#F7F8FC',muted:'#9099AA',line:'#252C39',violet:'#7966FF',cyan:'#4BD8FF',green:'#52DFA3',orange:'#FFB45C'};
export const s=StyleSheet.create({
 app:{flex:1,backgroundColor:C.bg},body:{flex:1},scroll:{padding:16,paddingBottom:104},
 header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:14},eyebrow:{color:'#7E8798',fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{color:C.text,fontSize:27,fontWeight:'900',letterSpacing:-.8},
 card:{backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:22,padding:17,marginBottom:11},heroRow:{flexDirection:'row',gap:12,alignItems:'center'},heroTitle:{color:C.text,fontSize:29,fontWeight:'900',letterSpacing:-1,marginTop:12},heroText:{color:C.muted,fontSize:12,lineHeight:18,marginTop:7},
 pill:{alignSelf:'flex-start',borderWidth:1,borderRadius:99,paddingHorizontal:9,paddingVertical:5},pillText:{fontSize:9,fontWeight:'900'},progress:{width:88,height:88,borderRadius:44,borderWidth:7,borderColor:C.cyan,alignItems:'center',justifyContent:'center'},progressN:{color:C.text,fontSize:21,fontWeight:'900'},progressS:{color:C.muted,fontSize:9},
 section:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:10,marginBottom:11},sectionTitle:{color:C.text,fontSize:19,fontWeight:'900'},link:{color:'#A7B6FF',fontSize:11,fontWeight:'800'},
 prayerRow:{flexDirection:'row',gap:5},prayer:{flex:1,borderWidth:1,borderColor:C.line,borderRadius:13,paddingVertical:9,alignItems:'center',backgroundColor:'#0D131D'},prayerDone:{borderColor:'#285E49',backgroundColor:'#10251D'},prayerName:{color:C.text,fontSize:8,fontWeight:'800'},prayerTime:{color:C.muted,fontSize:7,marginTop:2},
 timeline:{flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:C.line,backgroundColor:'#0D121B',borderRadius:16,padding:12,marginBottom:8},timelineDone:{opacity:.55},time:{width:58,color:'#A2AABC',fontSize:9,fontWeight:'800'},emoji:{width:36,height:36,borderRadius:11,backgroundColor:'#121D2A',alignItems:'center',justifyContent:'center'},timelineTitle:{color:C.text,fontSize:12,fontWeight:'850'},note:{color:C.muted,fontSize:9,marginTop:2},
 circle:{width:24,height:24,lineHeight:22,textAlign:'center',borderRadius:12,borderWidth:1,borderColor:'#414A5A',color:'#07100C',overflow:'hidden'},circleDone:{backgroundColor:C.green,borderColor:C.green},
 modeRow:{flexDirection:'row',gap:7,marginTop:10},mode:{flex:1,borderWidth:1,borderColor:C.line,backgroundColor:'#0D121B',borderRadius:15,paddingVertical:14,alignItems:'center'},modeOn:{borderColor:'#5C4DD0',backgroundColor:'#18143B'},modeText:{color:C.text,fontSize:10,fontWeight:'850',marginTop:5},
 task:{flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:C.line,backgroundColor:C.panel,borderRadius:17,padding:13,marginBottom:8},taskMeta:{color:'#7F899B',fontSize:8,fontWeight:'900'},taskTitle:{color:C.text,fontSize:13,fontWeight:'800',marginTop:3},delete:{color:'#727B8C',fontSize:22},
 add:{width:46,height:46,borderRadius:15,backgroundColor:C.violet,alignItems:'center',justifyContent:'center'},addText:{color:'#fff',fontSize:25},input:{minHeight:48,borderWidth:1,borderColor:C.line,backgroundColor:'#121824',color:C.text,borderRadius:14,paddingHorizontal:13,fontSize:16},button:{minHeight:47,borderRadius:14,backgroundColor:C.violet,alignItems:'center',justifyContent:'center',marginTop:12},buttonText:{color:'#fff',fontSize:12,fontWeight:'900'},
 tabs:{flexDirection:'row',gap:4,borderWidth:1,borderColor:C.line,borderRadius:14,padding:4,marginBottom:12},tab:{flex:1,paddingVertical:9,borderRadius:10,alignItems:'center'},tabOn:{backgroundColor:'#1B2230'},tabText:{color:C.text,fontSize:10,fontWeight:'800'},
 metricGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},metric:{width:'48.7%',backgroundColor:C.panel,borderWidth:1,borderColor:C.line,borderRadius:17,padding:14},metricT:{color:C.muted,fontSize:9},metricV:{color:C.text,fontSize:24,fontWeight:'900',marginVertical:7},bar:{height:5,borderRadius:99,backgroundColor:'#252B36',overflow:'hidden'},fill:{height:5,backgroundColor:C.cyan},timer:{color:C.text,fontSize:56,fontWeight:'900',textAlign:'center',letterSpacing:-2,marginVertical:15},
 nav:{position:'absolute',left:10,right:10,bottom:8,height:68,flexDirection:'row',padding:5,borderRadius:21,backgroundColor:'#0D121B',borderWidth:1,borderColor:C.line},navItem:{flex:1,alignItems:'center',justifyContent:'center',borderRadius:15},navOn:{backgroundColor:'#1A1735'},navText:{color:'#6D7689',fontSize:8,fontWeight:'800',marginTop:2},navEmoji:{fontSize:18},
 modal:{flex:1,justifyContent:'flex-end',backgroundColor:'#000000AA'},sheet:{backgroundColor:'#0C111A',borderTopLeftRadius:27,borderTopRightRadius:27,borderWidth:1,borderColor:C.line,padding:18,paddingBottom:28},sheetTitle:{color:C.text,fontSize:24,fontWeight:'900',marginBottom:13},
 crash:{flex:1,backgroundColor:C.bg,padding:22,justifyContent:'center'},crashTitle:{color:C.text,fontSize:23,fontWeight:'900',textAlign:'center'},crashText:{color:C.muted,fontSize:12,lineHeight:18,textAlign:'center',marginTop:9},errorBox:{borderWidth:1,borderColor:'#5B2731',backgroundColor:'#1B0F13',borderRadius:14,padding:12,marginTop:16},errorText:{color:'#FF9BA7',fontSize:11},loading:{flex:1,backgroundColor:C.bg,alignItems:'center',justifyContent:'center'},
});
